# -*- coding: utf-8 -*-
"""support_vector_machine_raisin_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sfHpxPibeFPWxGvZ8-B74s3CKAvHbjin

<h1 align="center">Support Vector Machine (SVM)</h1>

### Problem Statement:  Classify raisins into one of the two categories,
1. Kecimen
1. Besni
"""

import pandas as pd

df = pd.read_excel("Raisin_Dataset.xlsx")
df.sample(5)

df.shape

import seaborn as sns
import matplotlib.pyplot as plt

sns.pairplot(df, hue='Class', corner=True, diag_kind='kde')

for col in df.columns[:-1]:
    sns.boxplot(x='Class', y=col, data=df)
    plt.title(f"{col} vs Class")
    plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.drop('Class', axis=1).corr(), annot=True, cmap='coolwarm')

sns.jointplot(data=df, x='Area', y='Perimeter', hue='Class', kind='kde')

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X = df.drop('Class', axis=1)
y = df['Class']

X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
a
plt.figure(figsize=(8,6))
sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=y, palette='Set1')
plt.title("PCA Projection")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

"""There are total 900 records and using all the features that we have available, we will build a classification model by using support vector machine

### Train Test Split
"""

X = df[["Area", "MajorAxisLength", "MinorAxisLength", "Eccentricity", "ConvexArea", "Extent", "Perimeter"]]
y = df["Class"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

"""### Model Training Using SVM: RBF Kernel"""

from sklearn.svm import SVC

model = SVC(kernel="rbf")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print(report)

model.n_iter_

"""### Model Training Using SVM: Linear Kernel"""

from sklearn.svm import SVC

model = SVC(kernel="linear")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print(report)

model.n_iter_